# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    # note no ports - cannot be connected to from outside this set of services
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localdbpass
      POSTGRES_USER: localdb
      POSTGRES_DB: db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  uat:
    image: uat
    restart: always
    links:
      - "db:database"
    ports:
      - 9000:9000
    volumes:
      - ./universal-application-tool-0.0.1:/code
    build: .
    command: sbt ~run
