AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  DBAddress:
    Description: The address at which the database can be reached.
    Type: String
  DBPort:
    Description: The port on which the database can be reached.
    Type: String
  LBTargetName:
    Description: The load balancer target group to add new containers to.
    Type: String
  ContainerSecurityGroup:
    Description: The security group to use for the containers.
    Type: String
  PrivateSubnet1:
    Description: The private subnets to add the database to.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: The private subnet to add the database to.
    Type: AWS::EC2::Subnet::Id
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password for database access
    Type: String
  SecretKey:
    NoEcho: 'true'
    Description: Secret key for Play application
    Type: String
Resources:
  ecscluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
  ecsservice:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ecscluster'
      DesiredCount: 2
      TaskDefinition: !Ref 'ecstaskdef'
      LoadBalancers:
        - ContainerName: uat
          ContainerPort: 9000
          TargetGroupArn: !Ref 'LBTargetName'
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref 'ContainerSecurityGroup'
          Subnets:
            - !Ref 'PrivateSubnet1'
            - !Ref 'PrivateSubnet2'
  loggroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 90
  ecstaskdef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::405662711265:role/ecs-task-role
      NetworkMode: awsvpc
      Cpu: 1024
      Memory: 8192
      ContainerDefinitions:
        - Name: uat
          Image: public.ecr.aws/t1q6b4h2/universal-application-tool:latest
          Environment:
            - Name: DB_JDBC_STRING
              Value: !Join
                - ''
                - - jdbc:postgresql://
                  - !Ref 'DBAddress'
                  - ':'
                  - !Ref 'DBPort'
                  - /postgres
            - Name: DB_USERNAME
              Value: !Ref 'DBUsername'
            - Name: DB_PASSWORD
              Value: !Sub '{{resolve:secretsmanager:${DBPassword}}}'
            - Name: SECRET_KEY
              Value: !Sub '{{resolve:secretsmanager:${SecretKey}}}'
          Cpu: 1024
          Memory: 8192
          PortMappings:
            - ContainerPort: '9000'
              HostPort: '9000'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'loggroup'
              awslogs-region: us-west-2
              awslogs-stream-prefix: uatsrv
          Essential: true
  autoscalingtarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 2
      MaxCapacity: 5
      ResourceId: !Join ['/', [service, !Ref ecscluster, !GetAtt ecsservice.Name]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: arn:aws:iam::405662711265:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
  autoscalingpolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: UATAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref autoscalingtarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 75% CPU utilization
        TargetValue: 75
