AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  Timestamp:
    Description: Current timestamp in seconds.
    Type: Number
  DBUsername:
    Description: The name of the database user.
    Type: String
    Default: uat
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/network.yaml'
  Secrets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/secrets.yaml'
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/security_groups.yaml'
      Parameters:
        VPCId: !GetAtt 'VPC.Outputs.VPCId'
  LB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/load_balancer.yaml'
      Parameters:
        VPCId: !GetAtt 'VPC.Outputs.VPCId'
        PublicSubnet1: !GetAtt 'VPC.Outputs.PublicSubnet1'
        PublicSubnet2: !GetAtt 'VPC.Outputs.PublicSubnet2'
        LBSecurityGroup: !GetAtt 'SecurityGroups.Outputs.LbGroup'
  DB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/database.yaml'
      Parameters:
        DBUsername: !Ref DBUsername
        DBPassword: !GetAtt 'Secrets.Outputs.Password'
        DBSecurityGroup: !GetAtt 'SecurityGroups.Outputs.DatabaseGroup'
        PrivateSubnet1: !GetAtt 'VPC.Outputs.PrivateSubnet1'
        PrivateSubnet2: !GetAtt 'VPC.Outputs.PrivateSubnet2'
  Container:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/containers.yaml'
      Parameters:
        DBUsername: !Ref DBUsername
        DBPassword: !GetAtt 'Secrets.Outputs.Password'
        DBAddress: !GetAtt 'DB.Outputs.DBAddress'
        DBPort: !GetAtt 'DB.Outputs.DBPort'
        SecretKey: !GetAtt 'Secrets.Outputs.Key'
        PrivateSubnet1: !GetAtt 'VPC.Outputs.PrivateSubnet1'
        PrivateSubnet2: !GetAtt 'VPC.Outputs.PrivateSubnet2'
        LBTargetName: !GetAtt 'LB.Outputs.LBTarget'
        ContainerSecurityGroup: !GetAtt 'SecurityGroups.Outputs.ContainerGroup'
  StackTTL:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      # A template provided by AWS that automatically deletes the current stack after a number of minutes.
      TemplateURL: !Sub 'https://s3.amazonaws.com/seattle-uat-cftmpl/${Timestamp}/ttl.yaml'
      Parameters:
        StackName: !Ref 'AWS::StackName'
        TTL: '25'
    Condition: IsTest
Conditions:
  IsProd: !Equals
    - !Ref 'AWS::StackName'
    - "uat"
  IsTest: !Not 
    - !Equals
      - !Ref 'AWS::StackName'
      - "uat"
Outputs:
  WebRoot:
    Description: The DNS name of the load balancer.
    Value: !GetAtt 'LB.Outputs.LBEndpoint'
