name: pr_test

on:
  pull_request:
    branches: main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out pr branch
        uses: actions/checkout@v2
      - name: Run tests in tester
        run: docker build -t uat ./; docker run -v /var/run/docker.sock:/var/run/docker.sock uat sbt clean test
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        # Confirm that we get a response on port 9000.
        run: while ! docker run --network host appropriate/curl -v -s --retry-max-time 180 --retry-connrefused http://localhost:9000/ ; do sleep 5; done
        timeout-minutes: 3
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: check out pr branch
        uses: actions/checkout@v2
        if: contains(toJSON(steps.file_changes.outputs.files), 'infra/')
